// SPDX-License-Identifier: PMPL-1.0-or-later
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// Game Server Admin — A2ML serialisation and deserialisation
//
// Converts between ParsedConfig structures and A2ML (Annotated Attribute
// Markup Language) text.  A2ML is the canonical interchange format used
// by hyperpolymath projects for structured configuration.
//
// Output format:
//   @server(id="...", game="...", host="..."):
//     @probe(protocol="...", fingerprint="..."):@end
//     @config(format="...", path="..."):
//       @field(key="...", type="...", label="...", default="..."):
//         "Current Value"
//       @end
//     @end
//   @end

const std = @import("std");
const Allocator = std.mem.Allocator;
const config_extract = @import("config_extract.zig");
const game_profiles = @import("game_profiles.zig");
const main = @import("main.zig");

// ═══════════════════════════════════════════════════════════════════════════════
// Types
// ═══════════════════════════════════════════════════════════════════════════════

/// A single difference between two config versions.
pub const ConfigDiff = struct {
    key: []const u8,
    old_value: []const u8,
    new_value: []const u8,
    action: DiffAction,
};

/// The kind of change represented by a ConfigDiff.
pub const DiffAction = enum(u8) {
    Added = 0,
    Modified = 1,
    Removed = 2,
};

// ═══════════════════════════════════════════════════════════════════════════════
// A2ML emission
// ═══════════════════════════════════════════════════════════════════════════════

/// Emit a full A2ML document for a server configuration.
///
/// The output contains the server metadata block, an optional probe
/// block, and all config fields annotated with type/label/default
/// information from the game profile.
pub fn emitA2ML(
    allocator: Allocator,
    server_id: []const u8,
    game_id: []const u8,
    config: *const config_extract.ParsedConfig,
    profile: *const game_profiles.GameProfile,
) ![]const u8 {
    var buf = std.ArrayList(u8).init(allocator);
    errdefer buf.deinit();
    const writer = buf.writer();

    // SPDX header
    try writer.writeAll("# SPDX-License-Identifier: PMPL-1.0-or-later\n");
    try writer.writeAll("# Generated by Game Server Admin FFI layer\n\n");

    // Server block
    try writer.print("@server(id=\"{s}\", game=\"{s}\"):\n", .{ server_id, game_id });

    // Probe block (protocol and fingerprint from profile)
    try writer.print("  @probe(protocol=\"{s}\"):", .{profile.protocol});
    try writer.writeAll("@end\n");

    // Config block
    const format_name = formatToString(config.format);
    try writer.print("  @config(format=\"{s}\", path=\"{s}\"):\n", .{ format_name, config.path });

    // Emit each field
    for (config.fields.items) |field| {
        try emitField(&field, writer, profile);
    }

    try writer.writeAll("  @end\n");
    try writer.writeAll("@end\n");

    return buf.toOwnedSlice();
}

/// Emit a single config field as an A2ML @field block.
///
/// If a matching FieldDef exists in the profile, enriches the output
/// with type, label, default, and constraint information.
pub fn emitField(
    field: *const config_extract.ConfigField,
    writer: anytype,
    profile: *const game_profiles.GameProfile,
) !void {
    // Look up profile definition for this key
    const def = profile.getFieldDef(field.key);

    const field_type = if (def) |d| d.field_type else field.field_type;
    const label = if (def) |d| d.label else field.label;
    const default_val = if (def) |d| d.default_val else field.default_val;

    try writer.print("    @field(key=\"{s}\"", .{field.key});

    if (field_type.len > 0) {
        try writer.print(", type=\"{s}\"", .{field_type});
    }
    if (label.len > 0) {
        try writer.print(", label=\"{s}\"", .{label});
    }
    if (default_val.len > 0) {
        try writer.print(", default=\"{s}\"", .{default_val});
    }
    if (field.is_secret) {
        try writer.writeAll(", secret=\"true\"");
    }

    // Range constraints
    if (def) |d| {
        if (d.range_min) |rmin| {
            try writer.print(", min=\"{d}\"", .{rmin});
        }
        if (d.range_max) |rmax| {
            try writer.print(", max=\"{d}\"", .{rmax});
        }
    }

    try writer.writeAll("):\n");

    // Emit current value (secrets are redacted)
    if (field.is_secret) {
        try writer.writeAll("      \"[REDACTED]\"\n");
    } else {
        try writer.print("      \"{s}\"\n", .{field.value});
    }

    try writer.writeAll("    @end\n");
}

// ═══════════════════════════════════════════════════════════════════════════════
// A2ML parsing
// ═══════════════════════════════════════════════════════════════════════════════

/// Parse an A2ML document back into a structured ParsedConfig.
///
/// This is the inverse of emitA2ML.  It extracts @field blocks and
/// their values, reconstructing the config fields.
pub fn parseA2ML(allocator: Allocator, a2ml: []const u8) !config_extract.ParsedConfig {
    var config = config_extract.ParsedConfig.init(allocator, .KeyValue, "");
    errdefer config.deinit();
    config.raw_text = try allocator.dupe(u8, a2ml);

    // Parse @config format attribute
    if (std.mem.indexOf(u8, a2ml, "@config(")) |config_start| {
        const after_config = a2ml[config_start..];
        if (extractA2MLAttr(after_config, "format")) |fmt_str| {
            config.format = stringToFormat(fmt_str);
        }
        if (extractA2MLAttr(after_config, "path")) |path| {
            config.path = path;
        }
    }

    // Parse @field blocks
    var pos: usize = 0;
    while (pos < a2ml.len) {
        const field_start = std.mem.indexOfPos(u8, a2ml, pos, "@field(") orelse break;
        const field_end = std.mem.indexOfPos(u8, a2ml, field_start, "@end") orelse break;

        const field_block = a2ml[field_start..field_end];
        const attrs_end = std.mem.indexOfScalar(u8, field_block, ')') orelse {
            pos = field_end + 4;
            continue;
        };

        const attrs = field_block[7..attrs_end]; // skip "@field("

        const key = extractA2MLAttr(attrs, "key") orelse {
            pos = field_end + 4;
            continue;
        };
        const field_type = extractA2MLAttr(attrs, "type") orelse "";
        const label = extractA2MLAttr(attrs, "label") orelse "";
        const default_val = extractA2MLAttr(attrs, "default") orelse "";
        const is_secret_str = extractA2MLAttr(attrs, "secret");
        const is_secret = if (is_secret_str) |s| std.mem.eql(u8, s, "true") else false;

        // Extract value (the quoted string on the next line)
        const value_area = field_block[attrs_end + 1 ..];
        const value = extractQuotedValue(value_area) orelse "";

        // Parse min/max
        var range_min: ?f64 = null;
        var range_max: ?f64 = null;
        if (extractA2MLAttr(attrs, "min")) |min_str| {
            range_min = std.fmt.parseFloat(f64, min_str) catch null;
        }
        if (extractA2MLAttr(attrs, "max")) |max_str| {
            range_max = std.fmt.parseFloat(f64, max_str) catch null;
        }

        try config.addField(key, value, field_type, label, default_val, range_min, range_max, is_secret);

        pos = field_end + 4;
    }

    return config;
}

/// Extract a named attribute value from an A2ML attribute string.
/// Looks for `name="value"` patterns.
fn extractA2MLAttr(attrs: []const u8, name: []const u8) ?[]const u8 {
    var search_buf: [128]u8 = undefined;
    const search = std.fmt.bufPrint(&search_buf, "{s}=\"", .{name}) catch return null;

    if (std.mem.indexOf(u8, attrs, search)) |start| {
        const val_start = start + search.len;
        if (std.mem.indexOfScalarPos(u8, attrs, val_start, '"')) |val_end| {
            return attrs[val_start..val_end];
        }
    }
    return null;
}

/// Extract a quoted value from a block of text.
/// Looks for the first `"..."` on any line.
fn extractQuotedValue(text: []const u8) ?[]const u8 {
    var line_iter = std.mem.splitScalar(u8, text, '\n');
    while (line_iter.next()) |raw_line| {
        const line = std.mem.trim(u8, raw_line, " \t\r");
        if (line.len < 2) continue;
        if (line[0] == '"') {
            if (std.mem.lastIndexOfScalar(u8, line, '"')) |last_q| {
                if (last_q > 0) return line[1..last_q];
            }
        }
    }
    return null;
}

// ═══════════════════════════════════════════════════════════════════════════════
// Config diffing
// ═══════════════════════════════════════════════════════════════════════════════

/// Compute the differences between two configurations.
///
/// Returns a slice of ConfigDiff entries describing what changed.
pub fn diffConfigs(
    allocator: Allocator,
    old: *const config_extract.ParsedConfig,
    new: *const config_extract.ParsedConfig,
) ![]ConfigDiff {
    var diffs = std.ArrayList(ConfigDiff).init(allocator);
    errdefer diffs.deinit();

    // Find modified and removed fields
    for (old.fields.items) |old_field| {
        if (new.getField(old_field.key)) |new_field| {
            if (!std.mem.eql(u8, old_field.value, new_field.value)) {
                try diffs.append(.{
                    .key = try allocator.dupe(u8, old_field.key),
                    .old_value = try allocator.dupe(u8, old_field.value),
                    .new_value = try allocator.dupe(u8, new_field.value),
                    .action = .Modified,
                });
            }
        } else {
            try diffs.append(.{
                .key = try allocator.dupe(u8, old_field.key),
                .old_value = try allocator.dupe(u8, old_field.value),
                .new_value = "",
                .action = .Removed,
            });
        }
    }

    // Find added fields
    for (new.fields.items) |new_field| {
        if (old.getField(new_field.key) == null) {
            try diffs.append(.{
                .key = try allocator.dupe(u8, new_field.key),
                .old_value = "",
                .new_value = try allocator.dupe(u8, new_field.value),
                .action = .Added,
            });
        }
    }

    return diffs.toOwnedSlice();
}

/// Free a slice of ConfigDiff entries.
pub fn freeDiffs(allocator: Allocator, diffs: []ConfigDiff) void {
    for (diffs) |diff| {
        allocator.free(diff.key);
        if (diff.old_value.len > 0) allocator.free(diff.old_value);
        if (diff.new_value.len > 0) allocator.free(diff.new_value);
    }
    allocator.free(diffs);
}

/// Apply diffs to original config text, preserving the original format.
///
/// For key=value and INI formats, finds matching lines and replaces
/// values in place.  For JSON, re-serialises.  For other formats,
/// performs best-effort line replacement.
pub fn applyDiff(
    allocator: Allocator,
    original_text: []const u8,
    format: config_extract.ConfigFormat,
    diffs: []const ConfigDiff,
) ![]const u8 {
    var result = std.ArrayList(u8).init(allocator);
    errdefer result.deinit();
    const writer = result.writer();

    switch (format) {
        .KeyValue, .INI, .ENV, .TOML => {
            // Line-based replacement
            var line_iter = std.mem.splitScalar(u8, original_text, '\n');
            var first_line = true;

            while (line_iter.next()) |raw_line| {
                if (!first_line) try writer.writeByte('\n');
                first_line = false;

                const line = std.mem.trim(u8, raw_line, "\r");

                // Check if this line matches any diff
                var replaced = false;
                for (diffs) |diff| {
                    if (diff.action == .Removed) {
                        // Check if this line starts with the key
                        if (lineMatchesKey(line, diff.key)) {
                            // Skip this line (removed)
                            replaced = true;
                            break;
                        }
                    } else if (diff.action == .Modified) {
                        if (lineMatchesKey(line, diff.key)) {
                            // Replace the value
                            if (std.mem.indexOfScalar(u8, line, '=')) |eq_pos| {
                                try writer.writeAll(line[0 .. eq_pos + 1]);
                                try writer.writeAll(diff.new_value);
                                replaced = true;
                                break;
                            }
                        }
                    }
                }

                if (!replaced) {
                    try writer.writeAll(line);
                }
            }

            // Append added fields
            for (diffs) |diff| {
                if (diff.action == .Added) {
                    try writer.writeByte('\n');
                    try writer.print("{s}={s}", .{ diff.key, diff.new_value });
                }
            }
        },

        .JSON => {
            // Re-parse, apply changes, re-serialise
            var parsed = std.json.parseFromSlice(std.json.Value, allocator, original_text, .{}) catch {
                // Fallback: return original
                try writer.writeAll(original_text);
                return result.toOwnedSlice();
            };
            defer parsed.deinit();

            for (diffs) |diff| {
                switch (diff.action) {
                    .Modified, .Added => {
                        // For flat keys, set directly on root object
                        if (parsed.value == .object) {
                            const val = std.json.Value{ .string = diff.new_value };
                            parsed.value.object.put(diff.key, val) catch {};
                        }
                    },
                    .Removed => {
                        if (parsed.value == .object) {
                            _ = parsed.value.object.orderedRemove(diff.key);
                        }
                    },
                }
            }

            std.json.stringify(parsed.value, .{ .whitespace = .indent_2 }, writer) catch {
                try writer.writeAll(original_text);
            };

            return result.toOwnedSlice();
        },

        else => {
            // For XML, Lua, YAML: return original (applying diffs to these
            // formats requires more sophisticated editing)
            try writer.writeAll(original_text);
        },
    }

    return result.toOwnedSlice();
}

/// Check if a line's key portion matches the given key.
fn lineMatchesKey(line: []const u8, key: []const u8) bool {
    const trimmed = std.mem.trim(u8, line, " \t");
    if (trimmed.len == 0 or trimmed[0] == '#' or trimmed[0] == ';') return false;

    if (std.mem.indexOfScalar(u8, trimmed, '=')) |eq_pos| {
        const line_key = std.mem.trim(u8, trimmed[0..eq_pos], " \t");
        return std.mem.eql(u8, line_key, key);
    }
    return false;
}

// ═══════════════════════════════════════════════════════════════════════════════
// Format conversion helpers
// ═══════════════════════════════════════════════════════════════════════════════

fn formatToString(format: config_extract.ConfigFormat) []const u8 {
    return switch (format) {
        .XML => "xml",
        .INI => "ini",
        .JSON => "json",
        .ENV => "env",
        .YAML => "yaml",
        .TOML => "toml",
        .Lua => "lua",
        .KeyValue => "key-value",
    };
}

fn stringToFormat(s: []const u8) config_extract.ConfigFormat {
    if (std.mem.eql(u8, s, "xml")) return .XML;
    if (std.mem.eql(u8, s, "ini")) return .INI;
    if (std.mem.eql(u8, s, "json")) return .JSON;
    if (std.mem.eql(u8, s, "env")) return .ENV;
    if (std.mem.eql(u8, s, "yaml")) return .YAML;
    if (std.mem.eql(u8, s, "toml")) return .TOML;
    if (std.mem.eql(u8, s, "lua")) return .Lua;
    if (std.mem.eql(u8, s, "key-value")) return .KeyValue;
    return .KeyValue;
}

// ═══════════════════════════════════════════════════════════════════════════════
// Exported C ABI functions
// ═══════════════════════════════════════════════════════════════════════════════

threadlocal var emit_result_buf: [16384]u8 = undefined;

/// Convert a JSON config representation to A2ML.
export fn gossamer_gsa_a2ml_emit(
    config_json: [*:0]const u8,
) callconv(.C) [*:0]const u8 {
    const allocator = std.heap.c_allocator;
    const json_str = std.mem.span(config_json);

    var parsed = config_extract.parseJSON(allocator, json_str) catch {
        main.setErrorStr("JSON parse failed");
        return @as([*:0]const u8, @ptrCast(&[_:0]u8{ 'E', 'R', 'R' }));
    };
    defer parsed.deinit();

    // Create a minimal profile for emission
    var empty_profile = game_profiles.GameProfile.empty();

    const a2ml = emitA2ML(allocator, "unknown", "unknown", &parsed, &empty_profile) catch {
        main.setErrorStr("A2ML emit failed");
        return @as([*:0]const u8, @ptrCast(&[_:0]u8{ 'E', 'R', 'R' }));
    };
    defer allocator.free(a2ml);

    const copy_len = @min(a2ml.len, emit_result_buf.len - 1);
    @memcpy(emit_result_buf[0..copy_len], a2ml[0..copy_len]);
    emit_result_buf[copy_len] = 0;

    return @as([*:0]const u8, @ptrCast(&emit_result_buf));
}

threadlocal var parse_result_buf: [16384]u8 = undefined;

/// Parse A2ML back to a JSON representation.
export fn gossamer_gsa_a2ml_parse(
    a2ml_ptr: [*:0]const u8,
) callconv(.C) [*:0]const u8 {
    const allocator = std.heap.c_allocator;
    const a2ml_str = std.mem.span(a2ml_ptr);

    var config = parseA2ML(allocator, a2ml_str) catch {
        main.setErrorStr("A2ML parse failed");
        return @as([*:0]const u8, @ptrCast(&[_:0]u8{ 'E', 'R', 'R' }));
    };
    defer config.deinit();

    // Convert to JSON
    var json_buf = std.ArrayList(u8).init(allocator);
    defer json_buf.deinit();
    const writer = json_buf.writer();

    writer.writeAll("{") catch return @as([*:0]const u8, @ptrCast(&[_:0]u8{ 'E', 'R', 'R' }));
    for (config.fields.items, 0..) |field, i| {
        if (i > 0) writer.writeAll(",") catch {};
        writer.print("\"{s}\":\"{s}\"", .{ field.key, field.value }) catch {};
    }
    writer.writeAll("}") catch {};

    const json = json_buf.items;
    const copy_len = @min(json.len, parse_result_buf.len - 1);
    @memcpy(parse_result_buf[0..copy_len], json[0..copy_len]);
    parse_result_buf[copy_len] = 0;

    return @as([*:0]const u8, @ptrCast(&parse_result_buf));
}

// ═══════════════════════════════════════════════════════════════════════════════
// Unit tests
// ═══════════════════════════════════════════════════════════════════════════════

test "A2ML emit and parse round-trip" {
    const allocator = std.testing.allocator;

    // Create a config
    var config = config_extract.ParsedConfig.init(allocator, .KeyValue, "/data/server.properties");
    defer config.deinit();

    try config.addField("server-name", "Test Server", "string", "Server Name", "A Minecraft Server", null, null, false);
    try config.addField("max-players", "20", "int", "Max Players", "20", 1.0, 1000.0, false);
    try config.addField("rcon.password", "secret", "secret", "RCON Password", "", null, null, true);

    var profile = game_profiles.GameProfile.empty();

    // Emit A2ML
    const a2ml = try emitA2ML(allocator, "mc-1", "minecraft-java", &config, &profile);
    defer allocator.free(a2ml);

    // Verify it contains expected content
    try std.testing.expect(std.mem.indexOf(u8, a2ml, "@server(") != null);
    try std.testing.expect(std.mem.indexOf(u8, a2ml, "server-name") != null);
    try std.testing.expect(std.mem.indexOf(u8, a2ml, "max-players") != null);
    try std.testing.expect(std.mem.indexOf(u8, a2ml, "[REDACTED]") != null); // secret

    // Parse it back
    var parsed = try parseA2ML(allocator, a2ml);
    defer parsed.deinit();

    try std.testing.expectEqual(@as(usize, 3), parsed.fields.items.len);
    try std.testing.expectEqualStrings("server-name", parsed.fields.items[0].key);
    try std.testing.expectEqualStrings("Test Server", parsed.fields.items[0].value);
}

test "diff configs" {
    const allocator = std.testing.allocator;

    var old = config_extract.ParsedConfig.init(allocator, .KeyValue, "");
    defer old.deinit();
    try old.addField("name", "Old Name", "", "", "", null, null, false);
    try old.addField("port", "25565", "", "", "", null, null, false);
    try old.addField("removed", "gone", "", "", "", null, null, false);

    var new = config_extract.ParsedConfig.init(allocator, .KeyValue, "");
    defer new.deinit();
    try new.addField("name", "New Name", "", "", "", null, null, false);
    try new.addField("port", "25565", "", "", "", null, null, false);
    try new.addField("added", "new", "", "", "", null, null, false);

    const diffs = try diffConfigs(allocator, &old, &new);
    defer freeDiffs(allocator, diffs);

    try std.testing.expectEqual(@as(usize, 3), diffs.len);

    // Modified: name changed
    var found_modified = false;
    var found_removed = false;
    var found_added = false;
    for (diffs) |d| {
        if (std.mem.eql(u8, d.key, "name") and d.action == .Modified) found_modified = true;
        if (std.mem.eql(u8, d.key, "removed") and d.action == .Removed) found_removed = true;
        if (std.mem.eql(u8, d.key, "added") and d.action == .Added) found_added = true;
    }
    try std.testing.expect(found_modified);
    try std.testing.expect(found_removed);
    try std.testing.expect(found_added);
}

test "format round-trip" {
    try std.testing.expectEqual(config_extract.ConfigFormat.XML, stringToFormat("xml"));
    try std.testing.expectEqual(config_extract.ConfigFormat.JSON, stringToFormat("json"));
    try std.testing.expectEqual(config_extract.ConfigFormat.KeyValue, stringToFormat("key-value"));
    try std.testing.expectEqualStrings("xml", formatToString(.XML));
    try std.testing.expectEqualStrings("json", formatToString(.JSON));
}
