// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// @generated by scripts/gen_abi_expected.zig from src/interface/abi/Layout.idr
// DO NOT EDIT. Regenerate with: zig run scripts/gen_abi_expected.zig
//
// Canonical C-ABI layout numbers lifted from the machine-checked Idris2 model
// (GSA.ABI.Layout). Consumed by abi_layout.zig to assert that the Zig extern
// structs agree, byte-for-byte, with the proven Idris layout.

pub const Field = struct {
    name: []const u8,
    offset: u32,
    size: u32,
    alignment: u32,
};

pub const StructExpect = struct {
    name: []const u8,
    total_size: u32,
    struct_align: u32,
    fields: []const Field,
};

pub const ServerHandle = StructExpect{
    .name = "ServerHandle",
    .total_size = 16,
    .struct_align = 8,
    .fields = &.{
        .{ .name = "rawPtr", .offset = 0, .size = 4, .alignment = 4 },
        .{ .name = "serverId", .offset = 8, .size = 8, .alignment = 8 },
    },
};

pub const ProbeResult = StructExpect{
    .name = "ProbeResult",
    .total_size = 64,
    .struct_align = 8,
    .fields = &.{
        .{ .name = "gameId", .offset = 0, .size = 8, .alignment = 8 },
        .{ .name = "version", .offset = 8, .size = 8, .alignment = 8 },
        .{ .name = "protocol", .offset = 16, .size = 4, .alignment = 4 },
        .{ .name = "fingerprint", .offset = 24, .size = 8, .alignment = 8 },
        .{ .name = "configPaths", .offset = 32, .size = 8, .alignment = 8 },
        .{ .name = "pathCount", .offset = 40, .size = 4, .alignment = 4 },
        .{ .name = "host", .offset = 48, .size = 8, .alignment = 8 },
        .{ .name = "port", .offset = 56, .size = 4, .alignment = 4 },
    },
};

pub const ConfigField = StructExpect{
    .name = "ConfigField",
    .total_size = 64,
    .struct_align = 8,
    .fields = &.{
        .{ .name = "key", .offset = 0, .size = 8, .alignment = 8 },
        .{ .name = "value", .offset = 8, .size = 8, .alignment = 8 },
        .{ .name = "fieldType", .offset = 16, .size = 8, .alignment = 8 },
        .{ .name = "label", .offset = 24, .size = 8, .alignment = 8 },
        .{ .name = "defaultVal", .offset = 32, .size = 8, .alignment = 8 },
        .{ .name = "rangeMin", .offset = 40, .size = 4, .alignment = 4 },
        .{ .name = "rangeMax", .offset = 44, .size = 4, .alignment = 4 },
        .{ .name = "hasMin", .offset = 48, .size = 4, .alignment = 4 },
        .{ .name = "hasMax", .offset = 52, .size = 4, .alignment = 4 },
        .{ .name = "isSecret", .offset = 56, .size = 4, .alignment = 4 },
    },
};

pub const A2MLConfig = StructExpect{
    .name = "A2MLConfig",
    .total_size = 48,
    .struct_align = 8,
    .fields = &.{
        .{ .name = "serverId", .offset = 0, .size = 8, .alignment = 8 },
        .{ .name = "gameId", .offset = 8, .size = 8, .alignment = 8 },
        .{ .name = "format", .offset = 16, .size = 4, .alignment = 4 },
        .{ .name = "configPath", .offset = 24, .size = 8, .alignment = 8 },
        .{ .name = "fields", .offset = 32, .size = 8, .alignment = 8 },
        .{ .name = "fieldCount", .offset = 40, .size = 4, .alignment = 4 },
    },
};

pub const GameProfile = StructExpect{
    .name = "GameProfile",
    .total_size = 96,
    .struct_align = 8,
    .fields = &.{
        .{ .name = "id", .offset = 0, .size = 8, .alignment = 8 },
        .{ .name = "name", .offset = 8, .size = 8, .alignment = 8 },
        .{ .name = "engine", .offset = 16, .size = 8, .alignment = 8 },
        .{ .name = "ports", .offset = 24, .size = 8, .alignment = 8 },
        .{ .name = "portCount", .offset = 32, .size = 4, .alignment = 4 },
        .{ .name = "protocol", .offset = 36, .size = 4, .alignment = 4 },
        .{ .name = "fingerprintPattern", .offset = 40, .size = 8, .alignment = 8 },
        .{ .name = "configFormat", .offset = 48, .size = 4, .alignment = 4 },
        .{ .name = "configPath", .offset = 56, .size = 8, .alignment = 8 },
        .{ .name = "fieldDefs", .offset = 64, .size = 8, .alignment = 8 },
        .{ .name = "fieldDefCount", .offset = 72, .size = 4, .alignment = 4 },
        .{ .name = "actions", .offset = 80, .size = 8, .alignment = 8 },
        .{ .name = "actionCount", .offset = 88, .size = 4, .alignment = 4 },
    },
};

pub const ServerOctad = StructExpect{
    .name = "ServerOctad",
    .total_size = 112,
    .struct_align = 8,
    .fields = &.{
        .{ .name = "graphData", .offset = 0, .size = 8, .alignment = 8 },
        .{ .name = "vectorEmbedding", .offset = 8, .size = 8, .alignment = 8 },
        .{ .name = "vectorLen", .offset = 16, .size = 4, .alignment = 4 },
        .{ .name = "tensorMetrics", .offset = 24, .size = 8, .alignment = 8 },
        .{ .name = "tensorRows", .offset = 32, .size = 4, .alignment = 4 },
        .{ .name = "tensorCols", .offset = 36, .size = 4, .alignment = 4 },
        .{ .name = "semanticAnnotations", .offset = 40, .size = 8, .alignment = 8 },
        .{ .name = "annotationCount", .offset = 48, .size = 4, .alignment = 4 },
        .{ .name = "documentText", .offset = 56, .size = 8, .alignment = 8 },
        .{ .name = "temporalVersion", .offset = 64, .size = 8, .alignment = 8 },
        .{ .name = "provenanceHash", .offset = 72, .size = 8, .alignment = 8 },
        .{ .name = "hasSpatial", .offset = 80, .size = 4, .alignment = 4 },
        .{ .name = "spatialX", .offset = 88, .size = 8, .alignment = 8 },
        .{ .name = "spatialY", .offset = 96, .size = 8, .alignment = 8 },
        .{ .name = "spatialZ", .offset = 104, .size = 8, .alignment = 8 },
    },
};

pub const Fingerprint = StructExpect{
    .name = "Fingerprint",
    .total_size = 32,
    .struct_align = 8,
    .fields = &.{
        .{ .name = "host", .offset = 0, .size = 8, .alignment = 8 },
        .{ .name = "port", .offset = 8, .size = 4, .alignment = 4 },
        .{ .name = "protocol", .offset = 12, .size = 4, .alignment = 4 },
        .{ .name = "responseSignature", .offset = 16, .size = 8, .alignment = 8 },
        .{ .name = "latencyMs", .offset = 24, .size = 4, .alignment = 4 },
    },
};

pub const DriftReport = StructExpect{
    .name = "DriftReport",
    .total_size = 48,
    .struct_align = 8,
    .fields = &.{
        .{ .name = "serverId", .offset = 0, .size = 8, .alignment = 8 },
        .{ .name = "status", .offset = 8, .size = 4, .alignment = 4 },
        .{ .name = "configDrift", .offset = 16, .size = 8, .alignment = 8 },
        .{ .name = "semanticDrift", .offset = 24, .size = 8, .alignment = 8 },
        .{ .name = "temporalConsistency", .offset = 32, .size = 8, .alignment = 8 },
        .{ .name = "overallScore", .offset = 40, .size = 8, .alignment = 8 },
    },
};

pub const all = [_]StructExpect{ ServerHandle, ProbeResult, ConfigField, A2MLConfig, GameProfile, ServerOctad, Fingerprint, DriftReport };
